spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/authentication?serverTimezone=UTC&autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 19880602



jcode:
  basePackage: com.github.dactiv.xiaoshamu.authentication
  genController: true
  genService: true
  genEntity: true
  genDao: true
  genMapperXml: true
  stripPrefix: tb_
  ignoreProperties:
    - id
    - creationTime
  tableNames:
    - tb_member_user_initialization
    - tb_member_user
    - tb_resource
    - tb_group
    - tb_console_user